//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        public int acc_id { get; set; }
        public string acc_usuario { get; set; }
        public int acc_numeroId { get; set; }
        public string acc_laboratorioId { get; set; }
        public string acc_maquina { get; set; }
        public System.TimeSpan acc_horaEntrada { get; set; }
        public Nullable<System.DateTime> acc_fecha { get; set; }
        public string acc_periodo { get; set; }
        public string acc_materia { get; set; }
    
        public virtual LABORATORIO LABORATORIO { get; set; }
    }
}
