//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA
    {
        public int asis_id { get; set; }
        public Nullable<int> asis_profesorId { get; set; }
        public string asis_materiaId { get; set; }
        public string asis_grupoId { get; set; }
        public string asis_laboratorioId { get; set; }
        public Nullable<int> asis_alumnos { get; set; }
        public Nullable<System.TimeSpan> asis_horaEntrada { get; set; }
        public Nullable<System.TimeSpan> asis_horaSalida { get; set; }
        public Nullable<System.DateTime> asis_fecha { get; set; }
        public string asis_periodo { get; set; }
    
        public virtual LABORATORIO LABORATORIO { get; set; }
        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
    }
}
