//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int bit_id { get; set; }
        public string bit_usuario { get; set; }
        public string bit_descripcion { get; set; }
        public Nullable<System.DateTime> bit_fecha { get; set; }
    }
}
