//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMBIOS
    {
        public int cambio_id { get; set; }
        public string cambio_serieGrp { get; set; }
        public string cambio_lab { get; set; }
        public string cambio_labNuevo { get; set; }
        public string cambio_horaEntrada { get; set; }
        public string cambio_horaSalida { get; set; }
        public string cambio_horaEntradaNueva { get; set; }
        public string cambio_horaSalidaNueva { get; set; }
        public string cambio_dia { get; set; }
        public string cambio_diaNuevo { get; set; }
        public string cambio_razonCambio { get; set; }
        public string cambio_fecha { get; set; }
        public string cam_periodo { get; set; }
    }
}
