//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPARTIDOS
    {
        public string grpCom_serie { get; set; }
        public string grpCom_grpId { get; set; }
        public string grpCom_materia { get; set; }
        public Nullable<int> grpCom_profesor { get; set; }
        public string grpCom_carGrpUno { get; set; }
        public string grpCom_carGrpDos { get; set; }
        public string grpCom_grpUno { get; set; }
        public string grpCom_grpDos { get; set; }
    }
}
