//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        public int cur_id { get; set; }
        public string cur_nombre { get; set; }
        public Nullable<int> cur_profesorId { get; set; }
        public string cur_laboratorioId { get; set; }
        public System.TimeSpan cur_horaEntrada { get; set; }
        public System.TimeSpan cur_horaSalida { get; set; }
        public System.DateTime cur_fecha { get; set; }
        public string cur_presentador { get; set; }
        public string cur_periodo { get; set; }
        public string cur_dia { get; set; }
    
        public virtual LABORATORIO LABORATORIO { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
    }
}
