//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FALTAS
    {
        public int fal_id { get; set; }
        public Nullable<int> fal_profesorId { get; set; }
        public string fal_materiaId { get; set; }
        public Nullable<int> fal_grupoId { get; set; }
        public string fal_laboratorioId { get; set; }
        public string fal_hora { get; set; }
        public string fal_motivo { get; set; }
    
        public virtual LABORATORIO LABORATORIO { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
