//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATGRP
    {
        public string matgrp_nombre { get; set; }
        public string materia { get; set; }
        public string grupo { get; set; }
        public Nullable<int> hora { get; set; }
        public string periodo { get; set; }
        public string matgrp_serie { get; set; }
    }
}
